### ISSUE TITLE
Bad jmespath expression: Unknown token '='

### ISSUE THREAD

**Issue by js-truework** [alastairmccormack/ecs-tunnel#2]
It seems that when including `-n` in my ecs-tunnel args, I get a LexerError as seen below. I've redacted resource identifiers in the traceback / commandline, but I don't think they should matter for this particular error.

## Environment

```
➜ ecs-tunnel --version
ecs-tunnel, version 0.3.1
➜ python --version
Python 3.9.7
➜ uname -a
Darwin Jasons-MacBook-Pro.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64
```

## Traceback

```
➜ ecs-tunnel -L 5432:<my_rds_instance>:5432 -c <my_cluster_name> -t <my_task_identifier> -n <my_container_name> --profile staging-admin
Traceback (most recent call last):
  File "/Users/jason/.local/bin/ecs-tunnel", line 8, in <module>
    sys.exit(cli())
  File "/Users/jason/.local/pipx/venvs/ecs-tunnel/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jason/.local/pipx/venvs/ecs-tunnel/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/jason/.local/pipx/venvs/ecs-tunnel/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jason/.local/pipx/venvs/ecs-tunnel/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jason/.local/pipx/venvs/ecs-tunnel/lib/python3.9/site-packages/ecs_tunnel/cli.py", line 94, in cli
    et = EcsTunnel(
  File "/Users/jason/.local/pipx/venvs/ecs-tunnel/lib/python3.9/site-packages/ecs_tunnel/_ecs_tunnel.py", line 66, in __init__
    self._ssm_target_id = self._get_task_id()
  File "/Users/jason/.local/pipx/venvs/ecs-tunnel/lib/python3.9/site-packages/ecs_tunnel/_ecs_tunnel.py", line 89, in _get_task_id
    container_runtime_id = jmespath.search(
  File "/Users/jason/.local/pipx/venvs/ecs-tunnel/lib/python3.9/site-packages/jmespath/__init__.py", line 23, in search
    return parser.Parser().parse(expression).search(data, options=options)
  File "/Users/jason/.local/pipx/venvs/ecs-tunnel/lib/python3.9/site-packages/jmespath/parser.py", line 88, in parse
    parsed_result = self._do_parse(expression)
  File "/Users/jason/.local/pipx/venvs/ecs-tunnel/lib/python3.9/site-packages/jmespath/parser.py", line 96, in _do_parse
    return self._parse(expression)
  File "/Users/jason/.local/pipx/venvs/ecs-tunnel/lib/python3.9/site-packages/jmespath/parser.py", line 109, in _parse
    self._tokens = list(self.tokenizer)
  File "/Users/jason/.local/pipx/venvs/ecs-tunnel/lib/python3.9/site-packages/jmespath/lexer.py", line 102, in tokenize
    raise LexerError(
jmespath.exceptions.LexerError: Bad jmespath expression: Unknown token '=':
tasks[0].containers[?name = '<my_container_name>'].runtimeId
```

**Comment by alastairmccormack** [comment]
Hi @js-truework - many thanks for your report and apologies for the delay.

I've made a fix which is available in 0.3.2 from Pypi. 

Enjoy!
